import type { Metadata } from "next";
import { Inter, Cairo } from "next/font/google";
import "../globals.css";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "@/providers/theme-provider";
import { organizationSchema, websiteSchema } from "@/lib/seo/schema";
import JsonLd from "@/common/seo/JsonLd";
import { Toaster } from "sonner";
import Navbar from "@/layout/navbar/Navbar";
import Footer from "@/layout/footer/Footer";
import ThemeTransitionLayer from "@/features/theme/ThemeTransitionLayer";
import RadialTransitionProvider from "@/providers/RadialTransitionProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={`${locale === "ar" ? cairo.className : inter.className}`}
      suppressHydrationWarning
    >
      <body className="min-h-screen flex flex-col">
        {/* SEO Scehma */}
        <JsonLd data={organizationSchema(locale)} />
        <JsonLd data={websiteSchema(locale)} />

        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            {/* <ThemeTransitionLayer /> */}
            <RadialTransitionProvider>
              <Navbar />
              <main className="grow">{children}</main>
              <Footer />
            </RadialTransitionProvider>

            <Toaster
              position={locale === "ar" ? "top-right" : "top-left"}
              closeButton
              richColors
            />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
